### ISSUE TITLE
unhashable type: 'list' error

### ISSUE THREAD

**Issue by ttxtea** [tomduck/pandoc-eqnos#31]
The following error is thrown upon using the `--filter pandoc-eqnos` argument.
~~~
    _get_label(v['t'], v['c']) in labels:
TypeError: unhashable type: 'list'
pandoc: Error running filter pandoc-eqnos
Filter returned error status 1
~~~

**Comment by ttxtea** [comment]
A sorry, just found out that I accidentally installed it with `pip3`. If it is installed with `pip2` there is no error and everything works splendidly! It might be prudent to test or warn the user if the wrong pip is used.

**Comment by tomduck** [comment]
Thanks for your feedback and sorry for the delay.  Everything should work fine with `pip3` -- I test on both python 2 and 3.  Are you still having trouble with it?

**Comment by tomduck** [comment]
In any case, I would need more information to act on this Issue.

**Comment by tomduck** [comment]
I'm assuming this report is no longer a concern.  Please re-open it if I am mistaken.

**Comment by ReichKV** [comment]
Hello,

I think i have the same issue. I am using pandoc 1.19.2.4 on Ubuntu 18.04

When i run
`pandoc RNC.tex --filter pandoc-eqnos  -o RNC.docx`

I get the following error message:

Traceback (most recent call last):
File "/home/RCV/.local/bin/pandoc-eqnos", line 11, in <module>
sys.exit(main())
File "/home/RCV/.local/lib/python3.6/site-packages/pandoc_eqnos.py", line 310, in main
altered)
  File "/home/RCV/.local/lib/python3.6/site-packages/pandoc_eqnos.py", line 308, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/home/RCV/.local/lib/python3.6/site-packages/pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "/home/RCV/.local/lib/python3.6/site-packages/pandocxnos/core.py", line 658, in process_refs
    _process_refs(value, labels)
  File "/home/RCV/.local/lib/python3.6/site-packages/pandocxnos/core.py", line 131, in wrapper
    ret = func(*args, **kwargs)
  File "/home/RCV/.local/lib/python3.6/site-packages/pandocxnos/core.py", line 613, in _process_refs
    _get_label(v['t'], v['c']) in labels:
TypeError: unhashable type: 'list'
pandoc: Error running filter pandoc-eqnos
Filter returned error status 1
