### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by ghost** [tomduck/pandoc-eqnos#33]
Hello,

I think i have the same  issue as in https://github.com/tomduck/pandoc-eqnos/issues/31. I am using pandoc 1.19.2.4 on Ubuntu 18.04

When i run
pandoc RNC.tex --filter pandoc-eqnos -o RNC.docx

I get the following error message:

Traceback (most recent call last):
File "/home/RCV/.local/bin/pandoc-eqnos", line 11, in
sys.exit(main())
File "/home/RCV/.local/lib/python3.6/site-packages/pandoc_eqnos.py", line 310, in main
altered)
File "/home/RCV/.local/lib/python3.6/site-packages/pandoc_eqnos.py", line 308, in
altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
File "/home/RCV/.local/lib/python3.6/site-packages/pandocfilters.py", line 111, in walk
item['c'] if 'c' in item else None, format, meta)
File "/home/RCV/.local/lib/python3.6/site-packages/pandocxnos/core.py", line 658, in process_refs
_process_refs(value, labels)
File "/home/RCV/.local/lib/python3.6/site-packages/pandocxnos/core.py", line 131, in wrapper
ret = func(*args, **kwargs)
File "/home/RCV/.local/lib/python3.6/site-packages/pandocxnos/core.py", line 613, in _process_refs
_get_label(v['t'], v['c']) in labels:
TypeError: unhashable type: 'list'
pandoc: Error running filter pandoc-eqnos
Filter returned error status 1

**Comment by tomduck** [comment]
Hi there.  It looks like you are trying to process a LaTeX source file with pandoc-fignos.  However, pandoc-eqnos is only for processing markdown documents.  I have edited the documentation to try to make that more clear.

Cheers,
Tom
