### ISSUE TITLE
RuntimeError: Cannot understand pandocversion=3.0.1

### ISSUE THREAD

**Issue by benmaier** [tomduck/pandoc-eqnos#68]
Hi, I got a compatibility error (I suppose). Any hints on how to resolve?

Comes from running a pandoc command with `--filter=pandas-eqnos`

```Traceback (most recent call last):
  File "/opt/homebrew/bin/pandoc-eqnos", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/pandoc_eqnos.py", line 493, in main
    PANDOCVERSION = pandocxnos.init(args.pandocversion, doc)
  File "/opt/homebrew/lib/python3.10/site-packages/pandocxnos/core.py", line 224, in init
    _PANDOCVERSION = _get_pandoc_version(pandocversion, doc)
  File "/opt/homebrew/lib/python3.10/site-packages/pandocxnos/core.py", line 179, in _get_pandoc_version
    raise RuntimeError(msg)
RuntimeError: Cannot understand pandocversion=3.0.1
```

**Comment by benmaier** [comment]
Source of problem: https://github.com/tomduck/pandoc-xnos/issues/28

**Comment by bollenn** [comment]
Just ran into the same issue, lets hope https://github.com/tomduck/pandoc-xnos/issues/28 gets merged soon...
